version: '3'

services:
  # The main application service
  womsoft:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - test-network
      
  # Chrome browser for Selenium tests
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "5900:5900"  # VNC port for viewing
      - "7900:7900"  # noVNC HTML interface
    shm_size: '2gb'
    environment:
      - VNC_NO_PASSWORD=1
    networks:
      - test-network
      
  # Test runner service
  selenium-tests:
    build: 
      context: .
      dockerfile: Dockerfile.selenium
    depends_on:
      womsoft:
        condition: service_healthy
      chrome:
        condition: service_started
    environment:
      - APP_URL=http://womsoft:8000
      - SELENIUM_REMOTE_URL=http://chrome:4444/wd/hub
      - PYTHONUNBUFFERED=1
      - TEST_MODE=true
    volumes:
      - .:/app
    networks:
      - test-network
    command: pytest -v -m "selenium"  # This is the correct command to run tests with the selenium marker

networks:
  test-network: