version: '3'

services:
  womsoft:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    
  # New test service
  tests:
    build: .
    volumes:
      - .:/app
    command: pytest -v -m "not selenium"
    depends_on:
      - womsoft